imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig','php']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         
        save_path: "%kernel.root_dir%/sessions"
        cookie_lifetime: 31536000
    fragments:       ~

# PDF Generator
knp_snappy:
    pdf:
        enabled:    true
        binary:     %wkhtmltopdf_path%
        options:    []

    image:
        enabled:    true
        binary:     %wkhtmltoimage_path%
        options:    []

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:          
        statut_a_supprimer:        %statut_a_supprimer%
        statut_en_edition:         %statut_en_edition%
        statut_en_ligne:           %statut_en_ligne%

        statut_non_commence:       %statut_non_commence%
        statut_non_resolu:         %statut_non_resolu%
        statut_resolu:             %statut_resolu%

        macro_type_normal:         %macro_type_normal%
        macro_type_erreur:         %macro_type_erreur%
        macro_type_indice:         %macro_type_indice%
        macro_type_info:           %macro_type_info%
        macro_type_correction:     %macro_type_correction%
        macro_type_radio:          %macro_type_radio%
        macro_type_checkbox:       %macro_type_checkbox%
        macro_type_vignettes:      %macro_type_vignettes%
        macro_type_fraction:       %macro_type_fraction%
        macro_type_tableau:        %macro_type_tableau%
        macro_type_tableau_analyse: %macro_type_tableau_analyse%
        macro_type_integrale:      %macro_type_integrale%

        element_type_text:         %element_type_text%
        element_type_maths:        %element_type_maths%
        element_type_br:           %element_type_br%
        element_type_case:         %element_type_case%
        element_type_case_puissance: %element_type_case_puissance%
        element_type_case_indice:  %element_type_case_indice%
        element_type_lien:         %element_type_lien%
        element_type_image:        %element_type_image%
        element_type_jsgbox:       %element_type_jsgbox%
        element_type_jsggraph:     %element_type_jsggraph%
        element_type_jsgdiag:      %element_type_jsgdiag%
        element_type_radiotick:    %element_type_radiotick%
        element_type_checkboxtick: %element_type_checkboxtick%
        element_type_vignette:     %element_type_vignette%
        element_type_numerateur:   %element_type_numerateur%
        element_type_denominateur: %element_type_denominateur%
        element_type_tr:           %element_type_tr%
        element_type_td:           %element_type_td%
        element_type_liste_der:    %element_type_liste_der%

        clavier_type_simple:       %clavier_type_simple%
        clavier_type_avancee:      %clavier_type_avancee%
        clavier_type_vecteur:      %clavier_type_vecteur%
        clavier_type_point:        %clavier_type_point%

        mapping_types:             %mapping_types%

        matiere_mathematiques:     %matiere_mathematiques%
        matiere_physique:          %matiere_physique%
        matiere_biologie:          %matiere_biologie%
        matiere_anglais:           %matiere_anglais%
        matiere_francais:          %matiere_francais%
        matiere_histoire:          %matiere_histoire%


# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [MajordeskAppBundle]
    # java: /usr/bin/java
    # java: C:\Program Files (x86)\Java\jre7\bin\java.exe
    java: %java_path%
    filters:
        cssrewrite: ~
        yui_js:
           jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar
        yui_css:
           jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }
