jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Majordesk\AppBundle\Entity\Eleve: sha512
        Majordesk\AppBundle\Entity\Client: sha512
        Majordesk\AppBundle\Entity\Professeur: sha512
        Majordesk\AppBundle\Entity\Admin: sha512
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_PARENTS:     ROLE_ELEVE
        ROLE_PROF:        ROLE_ELEVE
        ROLE_ADMIN:       [ROLE_ELEVE, ROLE_PROF]
        ROLE_SUPER_ADMIN: [ROLE_ELEVE, ROLE_PROF, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
            chain:
                providers: [eleve, client, admin, professeur, in_memory]

        eleve:
            entity: { class: Majordesk\AppBundle\Entity\Eleve, property: mail }
        client:
            entity: { class: Majordesk\AppBundle\Entity\Client, property: mail }
        professeur:
            entity: { class: Majordesk\AppBundle\Entity\Professeur, property: mail }
        admin:
            entity: { class: Majordesk\AppBundle\Entity\Admin, property: mail }
        in_memory:
            memory:
                users:
                    user:  { password: PBlqcK19, roles: [ 'ROLE_ELEVE' ] }
                    admin: { password: PBlqcK19, roles: [ 'ROLE_SUPER_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # main_login:
            # pattern: ^/(accueil|les-cours-Majorclass|la-plateforme-Majorclass|les-tarifs|l-equipe|login|inscription|inscription-1|inscription-2|inscription-3|mentions-legales|faq)$
            # anonymous: true

        main:
            pattern:        ^/(|connexion|login_check|logout|admin|eleve|professeur|parents|accueil|les-cours-Majorclass|la-plateforme-Majorclass|les-tarifs|l-equipe|login|inscription|inscription-1|inscription-2|inscription-3|mentions-legales|faq)
            anonymous:      ~
            provider:       chain_provider
            form_login:
                login_path: login
                check_path: login_check
                post_only:  true
                default_target_path: /connexion
            logout:
                path:       logout
                target:     /login
            remember_me:
                key:      %secret%
                lifetime: 31536000
            # switch_user: true

    access_control:
        - { path: ^/eleve/, role: ROLE_ELEVE }
        - { path: ^/professeur/, role: ROLE_PROF }
        - { path: ^/parents/, role: ROLE_PARENTS }
        - { path: ^/admin/, role: ROLE_ADMIN }
