<?php

namespace Majordesk\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ChapitreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChapitreRepository extends EntityRepository
{
	/**
	 * @return array des chapitres correspondant à une matiere
	 */
	public function search($query)
	{
		$qb = $this->createQueryBuilder('c');
		$qb		   ->join('c.programme','p')
				   ->where(
					  $qb->expr()->like('c.nom', ':query')
				   )
				   ->setParameter('query', '%'.$query.'%')
				   ->orderBy('p.id')
				   ;		   				   
			
		return $qb->getQuery()
			      ->getResult();
	}
	
	/**
	 * @return array des chapitres correspondant à une matiere
	 */
	public function getChapitresByMatiere($id)
	{
		$qb = $this->createQueryBuilder('c')
				   ->join('c.matiere', 'm')
				   ->where('m.id = :id')
				   ->setParameter('id', $id)
				   ->orderBy('c.numero', 'ASC');		   				   
			
		return $qb->getQuery()
			      ->getResult();
	}
	
	/**
	 * @return array des chapitres correspondant à une matiere et un programme
	 */
	public function getChapitresByMatiereAndProgramme($id_matiere, $id_programme)
	{
		$qb = $this->createQueryBuilder('c')
				   ->join('c.matiere', 'm')
				   ->join('c.programme', 'p')
				   ->where('m.id = :id_matiere')				   
				   ->andWhere('p.id = :id_programme')
				   ->setParameter('id_matiere', $id_matiere)	
				   ->setParameter('id_programme', $id_programme)
				   ->orderBy('c.numero', 'ASC');		   				   
			
		return $qb->getQuery()
			      ->getResult();
	}
}
