<?php

namespace Majordesk\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
	/**
	 * @return 
	 */
	public function getDestinatairesRecap()
	{
		$qb = $this->createQueryBuilder('c')
				   ->where('c.alertes = :value')
				   ->setParameter('value', 1);
			
		return $qb->getQuery()
			      ->getResult();
	}
}
