<?php

namespace Majordesk\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EleveMatiereRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EleveMatiereRepository extends EntityRepository
{
	/**
	 * @return query_builder des élèves n'ayant pas de professeur
	 */
	public function getEleveMatiereByEleveAndMatiere($id_eleve, $id_matiere)
	{
		$qb = $this->createQueryBuilder('e_m')
				   ->where('e_m.eleve = :id_eleve')
				   ->andWhere('e_m.matiere = :id_matiere')
				   ->setParameter('id_eleve',$id_eleve)
				   ->setParameter('id_matiere',$id_matiere)
				   ->setMaxResults(1);
				   
		return $qb->getQuery()
			      ->getOneOrNullResult();
	}
	
	/**
	 * @return query_builder des élèves n'ayant pas de professeur
	 */
	public function getRenewingPlateformAccess()
	{
		$today = new \Datetime("now", new \DateTimeZone('Europe/Paris'));
		$today->format('Y-m-d');
		
		$qb = $this->createQueryBuilder('e_m')
				   ->where('e_m.date_abonnement is not null')
				   ->andWhere('e_m.date_abonnement <= :today')
				   ->andWhere('e_m.prelevement_plateforme = 1')
				   ->setParameter('today',$today)
				   ;
				   
		return $qb->getQuery()
			      ->getResult();
	}
}
