<?php

namespace Majordesk\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FactureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FactureRepository extends EntityRepository
{
	/**
	 * @return query_builder des
	 */
	public function getFacturesLimit($id_famille, $lim)
	{
		$qb = $this->createQueryBuilder('fac')
				   ->join('fac.famille', 'fam')
				   ->where('fam.id = :id_famille')
				   ->setParameter('id_famille', $id_famille)
				   ->orderBy('fac.dateEmission','DESC')
				   ->setMaxResults($lim);
			
		return $qb->getQuery()
			      ->getResult();
	}
}
