<?php

namespace Majordesk\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FamilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilleRepository extends EntityRepository
{
	public function getFamillesWhoseCardExpiresNextMonth()
	{
		$date_expiration = new \Datetime("now", new \DateTimeZone('Europe/Paris'));
		$date_expiration->add(new \DateInterval('P1M'));
		$date_expiration->format('Y-m-01');
	
		$qb = $this->createQueryBuilder('f')
				   ->where('f.date_expiration = :date_expiration')
				   ->setParameter('date_expiration', $date_expiration)
				   ;
			
		return $qb->getQuery()
			      ->getResult();
	}
}
