<?php

namespace Majordesk\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModBriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModBriqueRepository extends EntityRepository
{
	/**
	 * @return query_builder des 
	 */
	public function getOrderedModBriquesInSuperBriquesByModExercice($id)
	{
		$qb = $this->createQueryBuilder('mb') 
				   ->join('mb.mod_question', 'mq')
				   ->join('mq.mod_exercice', 'me')
				   ->where('me.id = :id')
				   ->setParameter('id', $id)
				   ->orderBy('mb.numero', 'ASC');
			
		return $qb->getQuery()
			      ->getResult();
	}
	
	/**
	 * @return query_builder des 
	 */
	public function getOrderedModBriquesInComplementsByModExercice($id)
	{
		$qb = $this->createQueryBuilder('mb') 
				   ->join('mb.mod_complement', 'mc')
				   ->join('mc.mod_question', 'mq')
				   ->join('mq.mod_exercice', 'me')
				   ->where('me.id = :id')
				   ->setParameter('id', $id)
				   ->orderBy('mb.numero', 'ASC');
			
		return $qb->getQuery()
			      ->getResult();
	}
	
	/**
	 * @return query_builder des 
	 */
	public function getOrderedModBriquesInComplement($id)
	{
		$qb = $this->createQueryBuilder('mb') 
				   ->join('mb.mod_complement', 'mc')
				   ->where('mc.id = :id')
				   ->setParameter('id', $id)
				   ->orderBy('mb.numero', 'ASC');
			
		return $qb->getQuery()
			      ->getResult();
	}
	
	/**
	 * @return
	 */
	public function incrementModBriquesInSuperBrique($id_superbrique, $numero, $incr)
	{	
		$qb = $this->_em->createQueryBuilder()
		           ->update('Majordesk\AppBundle\Entity\ModBrique','mb')
				   ->set('mb.numero', 'mb.numero + :incr')
				   ->where('mb.mod_question = :id_superbrique') // car on ne peut pas faire de join dans un update (cf http://stackoverflow.com/questions/15293502/doctrine-query-builder-not-working-with-update-and-inner-join)
				   ->andWhere('mb.numero >= :numero')
				   ->setParameter('id_superbrique', $id_superbrique)
				   ->setParameter('numero', $numero)
				   ->setParameter('incr', $incr)
				   ;

		$qb->getQuery()
		   ->execute(); 
	}
	
	/**
	 * @return
	 */
	public function incrementModBriquesInComplement($id_complement, $numero, $incr)
	{	
		$qb = $this->_em->createQueryBuilder()
		           ->update('Majordesk\AppBundle\Entity\ModBrique','mb')
				   ->set('mb.numero', 'mb.numero + :incr')
				   ->where('mb.mod_complement = :id_complement') // car on ne peut pas faire de join dans un update (cf http://stackoverflow.com/questions/15293502/doctrine-query-builder-not-working-with-update-and-inner-join)
				   ->andWhere('mb.numero >= :numero')
				   ->setParameter('id_complement', $id_complement)
				   ->setParameter('numero', $numero)
				   ->setParameter('incr', $incr)
				   ;

		$qb->getQuery()
		   ->execute(); 
	}
}
