<?php

namespace Majordesk\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModComplementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModComplementRepository extends EntityRepository
{
	/**
	 * @return query_builder des 
	 */
	public function getOrderedModComplementsByModExercice($id)
	{
		$qb = $this->createQueryBuilder('mc') 
				   ->join('mc.mod_question', 'mq')
				   ->join('mq.mod_exercice', 'me')
				   ->where('me.id = :id')
				   ->setParameter('id', $id)
				   ->orderBy('mc.numero', 'DESC');
			
		return $qb->getQuery()
			      ->getResult();
	}
}
