<?php

namespace Majordesk\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModMappingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModMappingRepository extends EntityRepository
{
	/**
	 * @return query_builder des mod_mappings d'un mod_exercice ordonnés par leur numéro
	 */
	public function getOrderedModMappingsByModExerciceId($id)
	{
		$qb = $this->createQueryBuilder('mm')
				   ->join('mm.mod_question', 'mq')
				   ->join('mq.mod_exercice', 'me')   
				   ->where('me.id = :id')
				   ->setParameter('id', $id);
			
		return $qb->getQuery()
			      ->getResult();
	}
	
	/**
	 * @return query_builder des mod_mappings d'une mod_question ordonnés par leur numéro
	 */
	public function getOrderedModMappingsByModQuestionId($id)
	{
		$qb = $this->createQueryBuilder('mm')
				   ->join('mm.mod_question', 'mq')
				   ->where('mq.id = :id')
				   ->setParameter('id', $id);
			
		return $qb->getQuery()
			      ->getResult();
	}
}
