<?php

namespace Majordesk\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ModMacroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModMacroRepository extends EntityRepository
{
	/**
	 * @return query_builder des mod_macros d'une mod_question ordonnés par leur numéro
	 */
	public function getOrderedModMacrosByModQuestionId($id)
	{
		$qb = $this->createQueryBuilder('mm')			   
				   ->join('mm.mod_question', 'mq')
				   ->where('mq.id = :id')
				   ->setParameter('id', $id)
				   ->orderBy('mm.numero', 'ASC');
			
		return $qb->getQuery()
			      ->getResult();
	}
	
	/**
	 * @return query_builder des mod_macros d'un mod_exercice ordonnés par leur numéro
	 */
	public function getOrderedModMacrosExerciceByModExerciceId($id)
	{
		$qb = $this->createQueryBuilder('mm')				   
				   ->join('mm.mod_exercice', 'me')
				   ->where('me.id = :id')
				   ->setParameter('id', $id)
				   ->orderBy('mm.numero', 'ASC');
			
		return $qb->getQuery()
			      ->getResult();
	}

	/**
	 * @return query_builder des mod_macros d'une mod_question d'un mod_exercice ordonnés par leur numéro
	 */
	public function getOrderedModMacrosByModExerciceId($id)
	{
		$qb = $this->createQueryBuilder('mm')				   
				   ->join('mm.mod_question', 'mq')	   
				   ->join('mq.mod_exercice', 'me')
				   ->where('me.id = :id')
				   ->setParameter('id', $id)
				   ->orderBy('mm.numero', 'ASC');
			
		return $qb->getQuery()
			      ->getResult();
	}
}
