<?php

namespace Majordesk\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProfesseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfesseurRepository extends EntityRepository
{
	/**
	 * @return array des professeurs d'un élève d'id $id
	 */
	public function getProfesseursFilteredByEleve($id)
	{
		$qb = $this->createQueryBuilder('p')
				   ->join('p.eleves', 'e')
				   ->where('e.id = :id')
				   ->setParameter('id', $id);
			
		return $qb->getQuery()
			      ->getResult();
	}

	/**
	 * @return array des professeurs d'un élève d'id $id_eleve
	 */
	public function getProfesseursFilteredByEleveQb($id_eleve)
	{
		$qb = $this->createQueryBuilder('p')
				   ->join('p.eleves', 'e')
				   ->where('e.id = :id_eleve')
				   ->setParameter('id_eleve', $id_eleve);
			
		return $qb;
	}
	
	/**
	 * @return array des professeurs d'un élève d'id $id et enseignant la matière $id_matiere
	 */
	public function getProfesseurByEleveAndMatiere($id_eleve, $id_matiere)
	{
		$qb = $this->createQueryBuilder('p')
				   ->join('p.eleves', 'e')
				   ->join('p.matieres', 'm')
				   ->where('e.id = :id_eleve')
				   ->andWhere('m.id = :id_matiere')
				   ->setParameter('id_eleve', $id_eleve)
				   ->setParameter('id_matiere', $id_matiere)
				   ->setMaxResults(1);
			
		return $qb->getQuery()
			      ->getOneOrNullResult();
	}
	
	/**
	 * @return array des professeurs ayant pour disponibilités $lu, $ma,...
	 */
	public function getProfesseursFilteredByDisponibilites($lu, $ma, $me, $je, $ve, $sa, $di)
	{
		$qb = $this->createQueryBuilder('p')
				   ->join('p.disponibilites', 'd');
			if ($lu == 1)
			{
				$qb->andWhere('d.jour = :jour')
				   ->setParameter('jour', 'Lundi');
			}
			if ($ma == 1)
			{
				$qb->andWhere('d.jour = :jour')
				   ->setParameter('jour', 'Mardi');
			}
			if ($me == 1)
			{
				$qb->andWhere('d.jour = :jour')
				   ->setParameter('jour', 'Mercredi');
			}
			if ($je == 1)
			{
				$qb->andWhere('d.jour = :jour')
				   ->setParameter('jour', 'Jeudi');
			}
			if ($ve == 1)
			{
				$qb->andWhere('d.jour = :jour')
				   ->setParameter('jour', 'Vendredi');
			}
			if ($sa == 1)
			{
				$qb->andWhere('d.jour = :jour')
				   ->setParameter('jour', 'Samedi');
			}
			if ($di == 1)
			{
				$qb->andWhere('d.jour = :jour')
				   ->setParameter('jour', 'Dimanche');
			}
			
		return $qb->getQuery()
			      ->getResult();
	}
}
