<?php

namespace Majordesk\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RequeteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequeteRepository extends EntityRepository
{
	/**
	 * @return query_builder des 
	 */
	public function getLastRequete()
	{
		$qb = $this->createQueryBuilder('r') 
				   ->orderBy('r.numero_fichier', 'DESC')
				   ->setMaxResults(1)
				   ;
			
		return $qb->getQuery()
			      ->getSingleResult();
	}
}
