<?php

namespace Majordesk\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends EntityRepository
{
	/**
	 * @return la liste des cours aujourd'hui entre heureFin et heureDebut
	 */
	public function getTicketsByFamille($id_famille)
	{
		$today = new \Datetime("now", new \DateTimeZone('Europe/Paris'));
		$today->sub(new \DateInterval('P3M'));
		$date = $today->format('Y-m-d');
	
		$qb = $this->createQueryBuilder('t')
				   ->join('t.eleve', 'e')
				   ->join('e.famille', 'f')
				   ->where('f.id = :id_famille')
				   ->andWhere('t.date_cours > :date')
				   ->setParameter('id_famille', $id_famille)
				   ->setParameter('date', $date)
				   ->orderBy('t.date_cours', 'DESC');
			
		return $qb->getQuery()
			      ->getResult();
	}
	
	/**
	 * @return la liste des cours aujourd'hui entre heureFin et heureDebut
	 */
	public function getTicketsByProfesseur($id_professeur, $date_debut, $date_fin)
	{
		$qb = $this->createQueryBuilder('t')
				   ->join('t.professeur', 'p')
				   ->where('p.id = :id_professeur')
				   ->setParameter('id_professeur', $id_professeur)
				   ->orderBy('t.date_cours', 'DESC');
		
		$qb->andWhere($qb->expr()->between('t.date_cours', ':date_debut', ':date_fin'))
		   ->setParameter('date_debut', $date_debut, \Doctrine\DBAL\Types\Type::DATE)
		   ->setParameter('date_fin', $date_fin, \Doctrine\DBAL\Types\Type::DATE);
			
		return $qb->getQuery()
			      ->getResult();
	}
	
	/**
	 * @return la liste des cours aujourd'hui entre heureFin et heureDebut
	 */
	public function getLastTicketsByProfesseur($id_professeur, $limit)
	{
		$qb = $this->createQueryBuilder('t')
				   ->join('t.professeur', 'p')
				   ->where('p.id = :id_professeur')
				   ->setParameter('id_professeur', $id_professeur)
				   ->orderBy('t.date_cours', 'DESC')
				   ->setMaxResults($limit);
		
		// $qb->andWhere($qb->expr()->between('t.date_cours', ':date_debut', ':date_fin'))
		   // ->setParameter('date_debut', $date_debut, \Doctrine\DBAL\Types\Type::DATE)
		   // ->setParameter('date_fin', $date_fin, \Doctrine\DBAL\Types\Type::DATE);
			
		return $qb->getQuery()
			      ->getResult();
	}
	
	/**
	 * @return la liste des cours aujourd'hui entre heureFin et heureDebut
	 */
	public function getAllTickets()
	{
		$qb = $this->createQueryBuilder('t')
				   ->orderBy('t.date_ticket', 'DESC');
			
		return $qb->getQuery()
			      ->getResult();
	}
}
